pipeline {
  agent any
  stages {
    stage ("Docker build") {
      steps {
        dir('bulletin-board-app'){
        sh 'docker build -t devopstrainingschool/nodejs-jenkins .'
        }
      }
    }
  
  
  }
 





}
